resilience4j:
  circuitbreaker:
    instances:
      authService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      authService:
        maxAttempts: 3
        waitDuration: 2s

  ratelimiter:
    instances:
      authService:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0

  timelimiter:
    instances:
      authService:
        timeoutDuration: 3s
server:
  port: 8081