server:
  port: 8081
spring:
  application:
    name: auth-service

resilience4j:
  ratelimiter:
    instances:
      bookService:
        limitForPeriod: 5               # Gi?i h?n s? yêu c?u t?i ?a trong m?i chu k?
        limitRefreshPeriod: 10s       # Th?i gian làm m?i l?i s? yêu c?u (10 giây)
        timeoutDuration: 500ms           # Th?i gian ch? t?i ?a khi yêu c?u b? gi?i h?n

  circuitbreaker:
    instances:
      bookService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        slidingWindowSize: 10

  retry:
    instances:
      bookService:
        maxAttempts: 3
        waitDuration: 5s

  timelimiter:
    instances:
      bookService:
        timeoutDuration: 2s
logging:
  level:
    io.github.resilience4j.ratelimiter: DEBUG
