server:
  port: 8082

spring:
  application:
    name: product-service

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 2s

  ratelimiter:
    instances:
      productService:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0

  timelimiter:
    instances:
      productService:
        timeoutDuration: 3s
