version: '3.8'

services:
  product-service:
    build: .
    container_name: product-service
    ports:
      - "3101:3001"
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://mongo:27017/product-service
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5
    ports:
      - "27018:27017"      
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
