version: "3.8"
services:
  product-service:
    build: ./product-service
    ports:
      - "8082:8082"

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - product-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
