server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCB
                fallbackUri: forward:/fallback/auth
        - id: book-service
          uri: http://localhost:8082
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: bookCB
                fallbackUri: forward:/fallback/book
management:
  endpoints:
    web:
      exposure:
        include: "*"
